version: "3.3"
services:
  server:
    build: weak-server
    container_name: server
    mac_address: "02:02:02:02:02:55"
    networks:
      main_net:
        ipv4_address: 172.22.0.10
    command: bash -c "python3 /code/init.py && python3 /login-demo/app.py && tail -F /dev/null"
    environment:
      - NODE_ENV=development
      - DEBIAN_FRONTEND=noninteractive
    ports:
      - mode: host
        target: 80
      - mode: host
        target: 443
    cap_add:
      - NET_ADMIN

  client:
    build: weak-client
    container_name: client
    mac_address: "02:02:02:02:02:cc"
    networks:
      main_net:
        ipv4_address: 172.22.0.12
    command: bash -c "python3 /code/init.py && tail -F /dev/null"
    environment:
      - NODE_ENV=development
      - DEBIAN_FRONTEND=noninteractive
    cap_add:
      - NET_ADMIN
  
  mitm:
    build: mitm
    container_name: mitm
    mac_address: "02:02:02:02:02:ee"
    networks:
      main_net:
        ipv4_address: 172.22.0.11
    command: bash -c "python3 /code/init.py && tail -F /dev/null"
    environment:
      - NODE_ENV=development
      - DEBIAN_FRONTEND=noninteractive
      - TERM=XTERM
      - PYTHONUNBUFFERED=1
    volumes:
      - ./mitm:/code:rw
    ports: 
      - mode: host
        target: 5678
    cap_add:
      - NET_ADMIN

  cado:
    build: cado-nfs
    container_name: cado
    networks:
      main_net:
        ipv4_address: 172.22.0.13
    command: bash -c "python3 /opt/master.py"

  cado-ssh:
    build: cado-ssh
    container_name: cado-ssh
    networks:
      main_net:
        ipv4_address: 172.22.0.14
    command: bash -c "python3 /code/init.py"
    environment:
      - NODE_ENV=development
      - DEBIAN_FRONTEND=noninteractive
      - TERM=XTERM
      - PYTHONUNBUFFERED=1

  demo-shell-cc:
    build: demo-shell-cc
    container_name: cc
    mac_address: "02:02:02:02:02:33"
    networks:
      main_net:
        ipv4_address: 172.22.0.15
    command: bash -c "tail -F /dev/null"
    environment:
      - NODE_ENV=development
      - DEBIAN_FRONTEND=noninteractive
    ports:
      - mode: host
        target: 5000
    cap_add:
      - NET_ADMIN

networks:
  main_net:
    ipam:
      driver: default
      config:
        - subnet: 172.22.0.0/16
