FROM ubuntu:20.04
RUN apt-get update -y -qq &&\
    apt-get upgrade -y -qq &&\
    apt-get install python3 python3-pip -y -qq

RUN pip3 install Flask flask-cors

ENV FLASK_APP=/code/cc.py
ENV FLASK_RUN_HOST=0.0.0.0
ENV FLASK_RUN_PORT=5000
RUN echo 'alias start-cc="python3 -m flask run"' >> ~/.bashrc

WORKDIR /code
COPY ./cc.py .
